Office.create!([
                 { name: 'Secretaría General', renamed: 0 },
                 { name: 'Dirección de Asesoría Jurídica', renamed: 0 },
                 { name: 'Dirección de Gestión y Desarrollo de Personas', renamed: 0 },
                 { name: 'Dirección de Auditoría Interna', renamed: 0 },
                 { name: 'Secretaria de Administración y Finanzas', renamed: 0 },
                 { name: 'Departamento de Presupuesto', renamed: 0 },
                 { name: 'Departamento de Patrimonio', renamed: 0 },
                 { name: 'Departamento de Contabilidad', renamed: 0 },
                 { name: 'Departamento de Rendición de Cuentas', renamed: 0 },
                 { name: 'Departamento de Tesorería', renamed: 0 },
                 { name: 'Departamento de Informática', renamed: 0 },
                 { name: 'Departamento de Servicios Generales', renamed: 0 },
                 { name: 'Departamento de Transporte', renamed: 0 },
                 { name: 'Unidad de Compras', renamed: 0 },
                 { name: 'Unidad Operativa de Contrataciones', renamed: 0 },
                 { name: 'Secretaría de Obras Públicas y Transporte', renamed: 0 },
                 { name: 'Secretaría de Salud Pública', renamed: 0 },
                 { name: 'Secretaría de Educación y Ciencias', renamed: 0 },
                 { name: 'Secretaría de Ambiente', renamed: 0 },
                 { name: 'Secretaría de Relaciones Exteriores e Integración', renamed: 0 },
                 { name: 'Secretaría de Juventud', renamed: 0 },
                 { name: 'Secretaría de Deportes', renamed: 0 },
                 { name: 'Secretaría de Acción Social', renamed: 0 },
                 { name: 'Secretaría de la Mujer, Niñez y Adolescencia', renamed: 0 },
                 { name: 'Secretaría de Asuntos Municipales', renamed: 0 },
                 { name: 'Secretaria de Gestión y Reducción de Riesgos', renamed: 0 },
                 { name: 'Secretaría de Asuntos Indígenas', renamed: 0 },
                 { name: 'Secretaría de Turismo', renamed: 0 },
                 { name: 'Coordinación del Programa Ñemity .', renamed: 0 },
                 { name: 'Coordinación de Comunicación y Prensa', renamed: 0 },
                 { name: 'Departamento de Relaciones Públicas y Protocolo', renamed: 0 },
                 { name: 'Asesor de la Secretaría de Producción Agropecuaria', renamed: 0 },
                 { name: 'Unidad de Fiscalización de Contratos', renamed: 0 },
                 { name: 'Unidad de Control y Transparencia', renamed: 0 }
               ])
