default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: USER
  password: PASSWORD
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: memos_backend_dev